### ISSUE TITLE
Migrate asynctest to stdlib's AsyncMock

### ISSUE THREAD

**Issue by fabaff** [TomerFi/aioswitcher#150]
# Bug Report

**Describe the bug**</br>
Asynctest doesn't work with Python 3.8 and above.

Asynctest upstream is aware of this breakage and recommends using the built-in AsyncMock instead.

See also Martiusweb/asynctest#144 and Martiusweb/asynctest#126

**Comment by TomerFi** [comment]
Thank you.
I will take care of this.

**Comment by fabaff** [comment]
`asynctest` doesn't support Python 3.8 and 3.9 which is shippped by the distributions.

**Comment by fabaff** [comment]
Bump

**Comment by tirkarthi** [comment]
Note: If you need AsyncMock for version less than Python 3.8 you can use the mock backport on GitHub : https://github.com/testing-cabal/mock

**Comment by TomerFi** [comment]
Oops...
I somehow managed to miss all of the notifications for this conversation.
I'll fix the stale bot's configuration.

@fabaff 
I'm sorry I totally forgot this issue,
I might need a little help and guidance,
I haven't done python in along time.

I will take a look this weekend!
