### ISSUE TITLE
Incorrect response parser

### ISSUE THREAD

**Issue by IsraelShok** [TomerFi/aioswitcher#25]
File "/usr/local/lib/python3.7/site-packages/aioswitcher/api/messages.py", line 85, in initialize
    temp_power[2:4] + temp_power[0:2], 16)
ValueError: invalid literal for int() with base 16: b''

**Comment by OrBin** [comment]
I also have this issue, with Switcher V2 (firmware version 65.7)

**Comment by OrBin** [comment]
Updating to firmware version 72.36 (using the app) solved the issue.

**Comment by danielbenzvi** [comment]
Also happening here. My home assistant integration is now broken because of this. Firmware 3.32
