### ISSUE TITLE
Support more Switcher devices

### ISSUE THREAD

**Issue by TomerFi** [TomerFi/aioswitcher#273]
When this integration module was created,
The only device made available by the vendor to the market was the Switcher V2 water heater device.
As time went by, more device types and versions were made available.

This integration library should support most (if not all) of them.

**Comment by thecode** [comment]
I am documenting here the model names and their type values:
Official model names:
```txt
Switcher Power Plug
Switcher Runner
Switcher V2
Switcher Touch
Switcher V4
```

Type mapping (taken from https://github.com/nitaybz/switcher-js/blob/d2bdc85ba9b820eabfda1ae6471a1e9565efa6b8/src/udp.js#L10)

```python
const types = {
    'a8': 'power_plug',
    'a1': 'v2_qca',
    'a7': 'v2_esp',
    '0b': 'v3',
    '17': 'v4',
    '0f': 'mini',
    '01': 'runner',
    '02': 'runner_mini'
}
```
Note that runner models are using a different tcp & udp ports and will need larger changes to be supported.

Example model extract to be placed after https://github.com/TomerFi/aioswitcher/blob/f3c2a93655bc048f114da37f4c61b951409501a7/src/aioswitcher/bridge/messages.py#L90:

```python
self._model = hexlify(message[75:76]).decode(ENCODING_CODEC)
```
Verified that it returns the correct model for `v3` (touch) and `power_plug`

**Comment by TomerFi** [comment]
@thecode 
Going forward with this.
Do you have an idea what types work as-is with the current aioswitcher 1.x.x versions?

**Comment by thecode** [comment]
Switcher V2 / Touch (v3) and V4 should work as is.
Switcher Power Plug is working for on off control, but the device report a fixed value for the `auto_off` and will ignore the timer value in a `turn_on_with_timer` service call.
In my opinion once the model is available to HA the integration can hide the timer related service/attributes for `Power Plug`

Edit: I have not tested, but Switcher Mini should also work

**Comment by thecode** [comment]
I suggest to have two new properties for a device:
`model_type` which will return the raw type (e.g. `a8`, `a1`, `a7`) and `model_name` which will map the type to a name.
```python
# ... during message parsing:
self._model_type = hexlify(message[75:76]).decode(ENCODING_CODEC)

@property
def model_type(self) -> str:
    """str: Return the model type code."""
    return self._model_type

@property
def model_name(self) -> str:
    """str: Return the model name."""
    if self._model_type in MODEL_NAMES:
        return MODEL_NAMES[self._model_type]
    
    return f"Unknown ({model_type})"
 ```
 
 in `consts.py`
 ```python
 MODEL_NAMES = {
    "a8": "Switcher Power Plug",
    "a1": "Switcher V2 (qca)",
    "a7": "Switcher V2 (esp)",
    "0b": "Switcher Touch",
    "17": "Switcher V4",
    "0f": "Switcher Mini",
}
```

**Comment by TomerFi** [comment]
`consts.py` is no longer with us. :-)

In fact, the whole module is getting an extreme make-over.
You can follow the [big-refactoring branch](https://github.com/TomerFi/aioswitcher/tree/big-refactoring).
 I'm constantly pushing modifications, but I force-push often, so expect changes.

The model names are currently represented as a `DeviceType` enum:
https://github.com/TomerFi/aioswitcher/blob/big-refactoring/src/aioswitcher/devices/__init__.py#L23

**Comment by TomerFi** [comment]
BTW

As part of the big make-over and in order to support multiple devices of multiple types,
The UDP bridge is no longer keeping track of the previous state of the device,
As you can see [here](https://github.com/TomerFi/aioswitcher/blob/dev/src/aioswitcher/protocols.py#L116), the previous device state was used to calculate the `last_state_change` property.

I think this property exists only for HA's sake,
I really prefer not to retain the device's state history anymore.

Can you perhaps think of a solution from the user (HA component) for the `last_state_change` property?

**Comment by TomerFi** [comment]
You know what... actually scratch that.
I think I can handle this on the device's level.

**Comment by thecode** [comment]
I don't see that `last_state_change` is used anywhere in current `switcher_kis` integration. I don't think it is needed, maybe it was in the past. HA internal state machine does exactly that, it compares the current state vs previous state and will update the entity last state change time.

**Comment by TomerFi** [comment]
@thecode 

> Verified that it returns the correct model for `v3` (touch) and `power_plug`

And I can now verify [this](https://github.com/TomerFi/aioswitcher/issues/273#issuecomment-852057000) being the case for my V2 ESP.
:-)

**Comment by TomerFi** [comment]
> I don't see that `last_state_change` is used anywhere in current `switcher_kis` integration. I don't think it is needed, maybe it was in the past. HA internal state machine does exactly that, it compares the current state vs previous state and will update the entity last state change time.

Great!

**Comment by TomerFi** [comment]
> Switcher V2 / Touch (v3) and V4 should work as is.
> Switcher Power Plug is working for on off control, but the device report a fixed value for the `auto_off` and will ignore the timer value in a `turn_on_with_timer` service call.
> In my opinion once the model is available to HA the integration can hide the timer related service/attributes for `Power Plug`
> 
> Edit: I have not tested, but Switcher Mini should also work

That's actually a good idea, clarifying what are the property keys shared between device types,
We need to validate this table:

| property          | Power Plug | Switcher V2 (qca) | Switcher V2 (esp) | Switcher Touch | Switcher Mini | SwitcherV4 |
| :---------------- | :--------: | :---------------: | :---------------: | :------------: | :-----------: | :--------: |
| device_type       | X          | X                 | X                 | X              | X             | X          |
| device_state      | X          | X                 | X                 | X              | X             | X          |
| device_id         | X          | X                 | X                 | X              | X             | X          |
| last_data_update  | X          | X                 | X                 | X              | X             | X          |
| ip_address        | X          | X                 | X                 | X              | X             | X          |
| mac_address       | X          | X                 | X                 | X              | X             | X          |
| name              | X          | X                 | X                 | X              | X             | X          |
| remaining_time    |            | X                 | X                 | X              | X             | X          |
| auto_shutdown     |            | X                 | X                 | X              | X             | X          |
| power_consumption | X          | X                 | X                 | X              | X             | X          |
| electric_current  | X          | X                 | X                 | X              | X             | X          |

**Comment by thecode** [comment]
For the above table, I can confirm that Switcher V2 (both types) & Switcher Touch support all properties.
Note that `Switcher V4` is missing in your table.
Switch plug reports fixed dummy value in `remaining_time` and `auto_shutdown`, all other properties are ok.

**Comment by TomerFi** [comment]
I see...

So I'm gonna go out on the limb and assume the `mini` and the `v4`,
after checking what they are, both support all of the properties as well.

So basically the only exception here is the `power plug`, which doesn't have support for the `remaining_time` and `auto_shutdown` properties.

I've updated the above table, although its not quite needed anymore.
