### ISSUE TITLE
Use poethepoet as a poetry plugin

### ISSUE THREAD

**Issue by TomerFi** [TomerFi/aioswitcher#426]
### What did you had in mind?

The new *poethepoet* version:
https://github.com/nat-n/poethepoet/releases/tag/v0.12.0

Added a feature for running *poe* tasks as a plugin,
so:

```shell
poe test
```

cat become:

```shell
poetry run poe test
```

and we won't need to install *poethepoet* outside the virtual env anymore.
this is worth consideration, as it also looks like *dependabot* is just updating *pyproject.toml* and not *requirement.txt*.

**Comment by dolby360** [comment]
I'm not sure what it means "and we won't need to install poethepoet outside the virtual env anymore." poethepoet is in the requirements file isn't that installed in the venv?

**Comment by TomerFi** [comment]
@dolby360 

Currently, we have poetry configured in [pyproject.toml](https://github.com/TomerFi/aioswitcher/blob/7571a27838b208e88a64a052e765d16dfbc68d49/pyproject.toml#L66) for scripting purposes. Still, we also have it configured in [requirements.txt](https://github.com/TomerFi/aioswitcher/blob/7571a27838b208e88a64a052e765d16dfbc68d49/requirements.txt#L1) so it could be installed in Python's context, as done in most if not all of the workflows, i.e. the [pr workflow](https://github.com/TomerFi/aioswitcher/blob/7571a27838b208e88a64a052e765d16dfbc68d49/.github/workflows/pr.yml#L55), and as should be done by developers prior to working on a new contribution.

Since [poethepoet v0.12.0](https://github.com/nat-n/poethepoet/releases/tag/v0.12.0), it can be used as a plugin while using poetry >= 1.2.0,
currently, we use [1.1.14](https://github.com/TomerFi/aioswitcher/blob/7571a27838b208e88a64a052e765d16dfbc68d49/requirements.txt#L2), so this will need to be updated too.

I haven't dived into this further, basically, I noticed this new feature while watching poethepoet's releases, and I opened this issue accordingly, and that was it. So my knowledge on the matter is pretty limited.

But if I understand correctly if we use poethepoet as a plugin, we won't need it in Python's context and can remove it from requirements.txt, which will be good not only for obvious reasons but also for maintainability, we use dependabot to keep dependencies up-to-date, it only updates the first project file it finds, so it just updates pyproject.toml and I have the very annoying task of manually updating requirements.txt, it doesn't happen that often, so writing automation for it seemed like overkill, so I would gladly switch to plugin usage instead.

If you're up for this, maybe base your work off release/v3 so we can include it in the next release.

**Comment by dolby360** [comment]
OK I'll take this.

**Comment by TomerFi** [comment]
hmm... this might not be doable yet.
I just noticed that `poetry` 1.2.x is still a pre-release.
https://pypi.org/project/poetry/#history

**Comment by dolby360** [comment]
OK I'll wait until 1.2 release to work on this.

**Comment by TomerFi** [comment]
_poetry 1.2.0_ is [out](https://python-poetry.org/blog/announcing-poetry-1.2.0/) and integrated into this project in https://github.com/TomerFi/aioswitcher/commit/5717f858aa528d57074f5633ff242b1a46eb6e9c.

**Comment by TomerFi** [comment]
I was reading a bit about using _poethepoet_ as a [poetry plugin](https://github.com/nat-n/poethepoet#usage-as-a-poetry-plugin)...
seems to be an overkill for this issue, as its goal is to eliminate the need to install _poethepoet_ outside the virtual environment.
I seem to have missed the option to [add it inside the project](https://github.com/nat-n/poethepoet#installation) and using it with [poetry shell](https://python-poetry.org/docs/cli/#shell), looks like a better fit I think.

**Comment by TomerFi** [comment]
@dolby360 if you haven't started working on this...
I think I'll handle it.

**Comment by dolby360** [comment]
No I haven't

**Comment by TomerFi** [comment]
Cool, cause I was just working on something else in this project, and I can include this too.
