### ISSUE TITLE
Depecrection warnings from pytest-asyncio should be handled

### ISSUE THREAD

**Issue by TomerFi** [TomerFi/aioswitcher#427]
### What did you had in mind?

Version 0.17 brought on some changes in regards to the *asyncio marker*.
https://github.com/pytest-dev/pytest-asyncio/releases/tag/v0.17.2

We should consider switching from using `@pytest.mark.asyncio` as marker with the `asyncio-mode=auto` or `asyncio-mode=legacy` configuration (legacy is the default), 
to using `@pytest_asyncio.fixture` as and the new `asyncio-mode=strict` configuration.

### Are you trying to fix a problem?

For now, *pytest-asyncio* only displays deprecation warnings:
https://github.com/TomerFi/aioswitcher/runs/4849025898?check_suite_focus=true

```shell
.venv/lib/python3.9/site-packages/pytest_asyncio/plugin.py:191
  /home/runner/work/aioswitcher/aioswitcher/.venv/lib/python3.9/site-packages/pytest_asyncio/plugin.py:191: DeprecationWarning: The 'asyncio_mode' default value will change to 'strict' in future, please explicitly use 'asyncio_mode=strict' or 'asyncio_mode=auto' in pytest configuration file.
    config.issue_config_time_warning(LEGACY_MODE, stacklevel=2)
```

We should handle this before it gets deprecated completely.

**Comment by TomerFi** [comment]
this will be auto-closed when [release/v3](https://github.com/TomerFi/aioswitcher/tree/release/v3) get's merged to the `dev` branch.

**Comment by thecode** [comment]
I wonder why this is not closed automatically, I think we can close it

**Comment by TomerFi** [comment]
Fixed in https://github.com/TomerFi/aioswitcher/pull/546
