### ISSUE TITLE
Better documentation site

### ISSUE THREAD

**Issue by TomerFi** [TomerFi/aioswitcher#442]
### What did you had in mind?

Replace `sphinx` with `mkdocs` which seems better for this project.

For refs, [this](https://aioswitcher.tomfi.info/) is the docs site for this project build with `sphinx`,
and [this](https://archetypes.tomfi.info/) is a docs site built for another project of mine, build with `mkdocs`.

**Comment by dolby360** [comment]
I'll take this :)

**Comment by TomerFi** [comment]
@dolby360 thank you very much for your willingness for contributing,
your contribution will be very much appreciated.

Please note:
We're currently working on a new release adding support for new devices and probably breaking some stuff up.
So please base your work on the [release/v3 branch](https://github.com/TomerFi/aioswitcher/tree/release/v3).
You can keep updated and interact with the rest of the contributors in the [designated discussion](https://github.com/TomerFi/aioswitcher/discussions/498) for this release.
You can also take a look at currently open (and recently closed) PRs to see recent changes.

🙏🏻

**Comment by dolby360** [comment]
You can close this :)

**Comment by TomerFi** [comment]
It's linked to the merged PR, it should be closed automatically once `release/v3` will get merged into the `dev` branch.

**Comment by TomerFi** [comment]
Fixed in https://github.com/TomerFi/aioswitcher/pull/546
