### ISSUE TITLE
trace error on initalization

### ISSUE THREAD

**Issue by ohadlevy** [TomerFi/aioswitcher#5]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aioswitcher/api/messages.py", line 84, in initialize
    temp_power[2:4] + temp_power[0:2], 16)
ValueError: invalid literal for int() with base 16: b''
```

this is using home assistant 0.94.1
thanks

**Comment by TomerFi** [comment]
Hey

Thank you for reporting this issue.
Unfortunately there's not much I can do about this specific error.
It's kind of a known issue, you just have to wait it out.
I'll explain...

The device sends out a broadcast message containing the current status approximately **every 4 seconds**.
The `aioswitcher` module grabs that message and parses it.
In some cases, the message just comes empty or broken which leads to this error, as you can see `b''`, meaning the incoming argument to this method was empty.

It can either be a network issue "cutting down" the message or an endpoint issue, meaning the device itself.
As this is an **unofficial API**, there a limit to what we can investigate on the endpoint side.

But, now worries! :-)
As the device will send another message in about 4 seconds,
you can safety ignore this error unless you see it repeats itself every 4 seconds.

**Comment by ohadlevy** [comment]
thanks! I would suggest to simply catch this error and print a nicer warning into the log, so people can understand it better, for example:

```
invalid broadcast message from <x> received, ignoring...
```

**Comment by TomerFi** [comment]
I believe you are right, maybe a clarification of the error message is needed.

I think I should also add this to the wiki section, this question was already asked a couple of time in other forums, I think it's a good idea to have a place to reference people to.

Thanks.
👍 
:-)
