### ISSUE TITLE
Breeze device not recognized by discover_devices script 

### ISSUE THREAD

**Issue by oranja** [TomerFi/aioswitcher#558]
### What happened?

Hi folks,

I have a couple of Breeze devices online at the house, and I was super excited to learn about the latest releases of this library and https://github.com/home-assistant/core/pull/78596/.
So I couldn't wait and spawned a slim instance of Home Assistant patched with the PR. Unfortunately it didn't find any
So I figured I'll go back to the source and debug.

I verified with Wireshark that I see the broadcast packets to the right ports on the network.
However the script never stepped in to the packet parser function ([`_parse_device_from_datagram`](https://github.com/TomerFi/aioswitcher/blob/4a925d0328d99394740527848c87c1bde51e4ff2/src/aioswitcher/bridge.py#L61)).

I'm trying to see if I can fix this on my own and suggest a PR, but until then wanted to have the issue at least documented and open to discussion.

p.s.
I am really excited and appreciate this project, ever since I bought some Switcher Breeze devices a few weeks ago and found out about this library (through [HASS/switcher_kis](/home-assistant/core/tree/dev/homeassistant/components/switcher_kis)). The added support for Breeze devices came _exactly_ at the right time for me.

### Module Version

dev

### Device Type

Switcher Breeze

### Firmware Version

2.20

**Comment by oranja** [comment]
Update: I have this issue on my Fedora (35) machine.
Right now I'm writing from my macOS (12.6) and the devices were recognized immediately.

I'm looking into whether this is a privilege thing.
Anyway, the script + bridge are probably not at fault here.

**Comment by oranja** [comment]
Update 2: It always ends up being the firewall.
Once I opened UDP ports 20002 and 20003 and ran the script, the devices got discovered.
Same through the patched version of HASS.

Hopefully my trial & error helps other people as well.

**Comment by thecode** [comment]
> Update 2: It always ends up being the firewall. Once I opened UDP ports 20002 and 20003 and ran the script, the devices got discovered. Same through the patched version of HASS.
> 
> Hopefully my trial & error helps other people as well.

This is why it is better to spend 5 hours debugging instead of 2 minutes reading the docs 😄:
https://www.home-assistant.io/integrations/switcher_kis/#notes
And after the PR will be merged it will include 20003:
https://deploy-preview-24150--home-assistant-docs.netlify.app/integrations/switcher_kis/#notes

**Comment by oranja** [comment]
Surprisingly, I have read the docs and this paragraph multiple times. It
did not click in my mind because they are both on the exact same network
(wlan / subnet).

Perhaps the part about different networks can be edited?

**Comment by thecode** [comment]
Any improvement to documentation is welcome, you can press EDIT on the docs page and add your suggestions
