### ISSUE TITLE
Remove usage of get_event_loop from the docs

### ISSUE THREAD

**Issue by TomerFi** [TomerFi/aioswitcher#563]
### What did you have in mind?

In #561 we removed the usage of `get_event_loop` from our code.
We should also remove it from our documentation site and repo readme.

**Comment by Kesav890** [comment]
can i have this issue?

**Comment by TomerFi** [comment]
yours, thanx!

**Comment by Kesav890** [comment]
is it enough to just remove .get_event_loop from all lines or we should change something ?

**Comment by TomerFi** [comment]
Bases on https://github.com/TomerFi/aioswitcher/pull/561, I think we need to replace all occurrences of `asyncio.get_event_loop()` with `asyncio.run()`.

**Comment by Kesav890** [comment]
Ok thankyou

**Comment by Kesav890** [comment]
for example is it like converting 
asyncio.get_event_loop().run_until_complete(print_devices(60))
as
asyncio.run_until_complete(print_devices(60))

or

asyncio.run().run_until_complete(print_devices(60))

**Comment by TomerFi** [comment]
actually I'm not sure, I'm not following python's versions close enough to answer without reading the docs first.
@oranja as the author of #561 can you pitch in on this?

**Comment by TomerFi** [comment]
@Kesav890 
I found some time to read a bit.
Let's use the high-level `run` function:

```python
asyncio.run(print_devices(60))
```

**Comment by Kesav890** [comment]
Oh thankyou
