### ISSUE TITLE
control_device script docs outdated

### ISSUE THREAD

**Issue by thecode** [TomerFi/aioswitcher#574]
### What happened?

Currently the [docs ](https://aioswitcher.tomfi.info/scripts/#scriptcontrol_devicepy)and the code inside the script show the following example:
https://github.com/TomerFi/aioswitcher/blob/558b1f61355747748717038ff9c3110aa73c1d1e/scripts/control_device.py#L39

However if run as instructed it will result with an error:
```
python control_device.py -d "ab1c2d" -i "111.222.11.22" turn_on
```
Result:
```
usage: control_device.py [-h]
                         {control_thermostat,create_schedule,delete_schedule,get_schedules,get_state,get_thermostat_state,set_auto_shutdown,set_name,set_shutter_position,stop_shutter,turn_off,turn_on}
                         ...
control_device.py: error: argument action: invalid choice: 'ab1c2d' (choose from 'control_thermostat', 'create_schedule', 'delete_schedule', 'get_schedules', 'get_state', 'get_thermostat_state', 'set_auto_shutdown', 'set_name', 'set_shutter_position', 'stop_shutter', 'turn_off', 'turn_on')
```

It looks like this was changed by https://github.com/TomerFi/aioswitcher/commit/9bb3aa40a03fa7694adf4a0d24a86c3c7d415a05

When running like this:
```
python control_device.py turn_on -d "ab1c2d" -i "111.222.11.22" 
```

It will work

I think setting the desired command (e.g, `turn_on`, `control_thermostat`) before the `device_id` and `device_ip` is preferred, but we need to update the script and docs to be aligned with that.

### Module Version

3.0.4.dev0

### Device Type

Switcher V2

### Firmware Version

NA

**Comment by TomerFi** [comment]
> It looks like this was changed by [9bb3aa4](https://github.com/TomerFi/aioswitcher/commit/9bb3aa40a03fa7694adf4a0d24a86c3c7d415a05)

This fix was originated from https://github.com/TomerFi/aioswitcher/pull/557.

> When running like this:
> 
> ```
> python control_device.py turn_on -d "ab1c2d" -i "111.222.11.22" 
> ```
> 
> It will work
> 
> I think setting the desired command (e.g, `turn_on`, `control_thermostat`) before the `device_id` and `device_ip` is preferred, but we need to update the script and docs to be aligned with that.

yes, this is the prefered way, previously this was bug, we missed updating the documentation for this fix.
