### ISSUE TITLE
Github set-output deprecation notice

### ISSUE THREAD

**Issue by TomerFi** [TomerFi/aioswitcher#576]
### What did you have in mind?

`set-output` is deprecated:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

We use it in [.github/workflows/release.yml](https://github.com/TomerFi/aioswitcher/blob/dev/.github/workflows/release.yml).

### Are you trying to fix a problem?

Prepare for deprecation by GitHub.

### Any lead on how this feature can be implemented?

Using [environment files](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files).

**Comment by TomerFi** [comment]
For reference, an [example of using GITHUB_OUTPUT environment file](
https://github.com/TomerFi/version-bumper/pull/96/files#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R62).

**Comment by altmas5** [comment]
workflows on this repo do not use `set-output`

**Comment by TomerFi** [comment]
fixed in: https://github.com/TomerFi/aioswitcher/commit/9f3fdd9e9ccb45602a9cca2c222b88a50dd98bda
