### ISSUE TITLE
Switcher runner S12 support

### ISSUE THREAD

**Issue by ohadbenita** [TomerFi/aioswitcher#585]
### What did you have in mind?

Hi,

Currently there's support for the single shutter Switcher runner.
Switcher since then started producing a double-shutter single-light device called [Switcher Runner S12](https://switcher.co.il/%D7%9E%D7%95%D7%A6%D7%A8/runner-lights-s12/).
Any chance for adding support to it?

The current API (V2) is unable to nor discover neither control the S12 device.

### Are you trying to fix a problem?

Yes, add support to a new device

### Any lead on how this feature can be implemented?

Probably reverse engineer the new API or try to find out the ports open by the new device. I can help if needed.

**Comment by TomerFi** [comment]
@ohadbenita I missed this issue...
Thank you very much for reporting it.

**Comment by TomerFi** [comment]
The designated branch for working on this is [add-s12-support](https://github.com/TomerFi/aioswitcher/tree/add-s12-support)

**Comment by danielbublil** [comment]
any updates?

**Comment by TomerFi** [comment]
Unfortunately no.

**Comment by The-cpu-max** [comment]
I have the same problem
Is there anything new with this?

**Comment by YogevBokobza** [comment]
I am working on this.
Part of https://github.com/TomerFi/aioswitcher/pull/694

**Comment by moryoav** [comment]
@YogevBokobza - if you need a beta tester, I can help... I'm eager to try (I have the S11).

**Comment by The-cpu-max** [comment]
> I am working on this. Part of #694



> @YogevBokobza - if you need a beta tester, I can help... I'm eager to try (I have the S11).

i can try also

**Comment by YogevBokobza** [comment]
Thank you @moryoav and @The-cpu-max !
I have the device as well.
I know how to get this and S12 devices to work, There is a long discussion  about those devices here: https://github.com/TomerFi/aioswitcher/discussions/715
I am waiting for the other Devs to make progress.

If I need your help I will ask, Thanks again :)

**Comment by shoguevara** [comment]
Just FYI: 
The switcher has some odd bug: it's not guaranteed that your email will work for https://switcher.co.il/GetKey/ portal, so you will not be able to automatically receive the token. In that case you just need to contact them via support form in their web page - they will send you the token via email. Just be sure to use the one you used to register, just in case.
One very important note: before copying the token, disable the email text translation, as it messes the formatting and the token gets copied in some corrupted state. 
May be that info is worth putting somewhere?)
