### ISSUE TITLE
switcher version 5.3 is not working

### ISSUE THREAD

**Issue by regevbr** [TomerFi/aioswitcher#592]
### What happened?

A new release (5.3) of switchers are rolling out and the support of this library is lost

### Module Version

latest (HA)

### Device Type

Switcher Mini

### Firmware Version

5.3

### Relevant log output

@marcipar can you provide logs, please?

```shell
```

**Comment by thecode** [comment]
I am still waiting for a final list of ports from Switcher and devices to test it on.

**Comment by regevbr** [comment]
@thecode did you manage to get the post list already by any chance?

**Comment by regevbr** [comment]
@thecode this is still an on going issue :-( Is there any progress on it? thanks!

**Comment by regevbr** [comment]
Still an issue, hoping for good news

**Comment by urihersh** [comment]
I have the same issue with a new Switcher touch I added (I have 2 more switcher touch devices which works).
The firmware is 5.03 and not 5.3 as it seems. I see it broadcasts on UDP port 10002.

**Comment by liadav** [comment]
On newer firmware versions (>5) it looks like the broadcast discovery packets are being sent to port 10002 instead of 20002. A quick fix for my home-assistant env (workaround hack) without patching the code was to create a udp broadcast relay that forwards packets from 10002 to 20002.

**Comment by urihersh** [comment]
> On newer firmware versions (>5) it looks like the broadcast discovery packets are being sent to port 10002 instead of 20002. A quick fix for my home-assistant env (workaround hack) without patching the code was to create a udp broadcast relay that forwards packets from 10002 to 20002.

hey @liadav, what did you use for your workaround?

**Comment by TomerFi** [comment]
Fix is included in [3.3.0](https://github.com/TomerFi/aioswitcher/releases/tag/3.3.0).

**Comment by liri** [comment]
@TomerFi will that release be included soon in HA release?
Switcher Touch is verified in 3.3.0?

**Comment by TomerFi** [comment]
> @TomerFi will that release be included soon in HA release? Switcher Touch is verified in 3.3.0?

Looks version 3.3.0 was already updated in HA, https://github.com/home-assistant/core/pull/91215.
But I have no idea if a release including this modification was made.
