### ISSUE TITLE
Double entities created in HA for switcher runner

### ISSUE THREAD

**Issue by adizag** [TomerFi/aioswitcher#655]
### What happened?

once in a few days all of the shutter devices are recreated, duplicating the entities in them, so the original one is unavailable and the new one gets "_2" at the end.

I tried to delete the interaction and install it again but the problem repeated every time.

![switche runner 2](https://user-images.githubusercontent.com/17390016/233987974-ac8ffffe-c5de-45bb-b25b-97e35071a0d2.jpeg)

![switche runner 1](https://user-images.githubusercontent.com/17390016/233987975-00458dfc-6be9-4e7f-913b-f8aade43af85.jpeg)

### Module Version

3.2.1

### Device Type

Switcher Runner

### Firmware Version

1.79/2.11

**Comment by adizag** [comment]
@TomerFi 
@thecode

**Comment by TomerFi** [comment]
Hey thank you for reporting.
This issue should go in [HA](https://github.com/home-assistant/core)  for further investigation.

**Comment by adizag** [comment]
Shall I open a same one in HA?
