### ISSUE TITLE
Switcher Touch - discovered but no actionon from HA (related to home-assistant / core #91215)

### ISSUE THREAD

**Issue by adizag** [TomerFi/aioswitcher#656]
### What happened?

A new switcher touch was not discovered by HA, found this issue in HA/CORE [https://github.com/home-assistant/core/pull/91215].

I noticed it was merged into dev release of HA, but I can't comment there...
So I installed it and it was discovered. The problem is that HA can't control the switch. Seems like information is passing from the switch to HA but not the other way around. 
please see the video:

https://user-images.githubusercontent.com/17390016/233991500-9ef6fed9-7a9e-4a79-b7ba-8a7535c100c9.mp4

### Module Version

3.2.1

### Device Type

Switcher Touch (V3)

### Firmware Version

5.3

**Comment by adizag** [comment]
@TomerFi 
@thecode

**Comment by YuvalWS** [comment]
Exactly the same for me. Manually updated the integration, the discovery (UDP listen?) Works but can't control the switch. How can I help debug it? Do you know about some API breaking changes?

**Comment by TomerFi** [comment]
Duplicated:
https://github.com/home-assistant/core/issues/92269
