### ISSUE TITLE
Unable to run the 

### ISSUE THREAD

**Issue by dmatik** [TomerFi/aioswitcher#668]
### What happened?

When running a discovery script from cmd, failing on the below error.

`C:\Python310>python discover_devices.py 30
Traceback (most recent call last):
  File "C:\Python310\discover_devices.py", line 25, in <module>
    from aioswitcher.bridge import (
ImportError: cannot import name 'SWITCHER_UDP_PORT_TYPE2_NEW_VERSION' from 'aioswitcher.bridge' (C:\Python310\lib\site-packages\aioswitcher\bridge.py)`

pip was update to pip-23.1.2

### Module Version

3.3.0

### Device Type

Switcher Touch (V3)

### Firmware Version

NA

**Comment by TomerFi** [comment]
The script and the deployment were not synced.
Fixed in [3.4.0](https://github.com/TomerFi/aioswitcher/releases/tag/3.4.0).
