### ISSUE TITLE
Support for Swithcer smart light switches 

### ISSUE THREAD

**Issue by menaheme** [TomerFi/aioswitcher#696]
### What did you have in mind?

Please Support Switcher smart light switches so that Home Assistant can control them
I opened an [issue ](https://github.com/home-assistant/core/issues/96790) over at HA , but was directed here

**Comment by dudutwizer** [comment]
+1 . None of the lights are recognized. workaround: Switcher Homebrige plugin

**Comment by menaheme** [comment]
Is Homebridge another platform? Or is this a plug in for Home assistant?

**Comment by dudutwizer** [comment]
Another platform..

**Comment by YogevBokobza** [comment]
I am working of this kind of support
As part of https://github.com/TomerFi/aioswitcher/pull/694

**Comment by TheSpringBoy** [comment]
Hi!
Is there any update on this now that the s11 runner and light support came out?

**Comment by YogevBokobza** [comment]
> Hi! Is there any update on this now that the s11 runner and light support came out?

Hey :)
Yeah the lights are coming soon..

First I want to solve the Home Assistant side plus Switcher s12 and then lights can come right after :)

**Comment by Andrewb308** [comment]
Hi guys, hope this find you well!
I just bought the Switcher Runner S12 and Switcher Light L3, question is, do we have the support for Home Assistant already or should i return them?

**Comment by TheSpringBoy** [comment]
Still in progress.
You can do like me, install home bridge as an addon to home assiatant, and add the lights via the homebridge integration.
Works perfectly

**Comment by Andrewb308** [comment]
Hi @TheSpringBoy 
thank you for the quick response,
I tried to search for homebridge in integrations and didnt find, is that a repository?
If so can you share with me the link to it?

**Comment by TheSpringBoy** [comment]
Hi
Yes it's an addon from a repository, install it from settings - add-ons - add on store - 3 dots - repositories.
https://github.com/davide125/hassio-addons

After that you have a web ui to configure the switcher integration inside homebridge.

You need to get a token from switcher in order for the lights control to work.
Get it at https://switcher.co.il/GetKey/

After it's all working on home bridge you can add it as a device from ha using the built in Apple HomKit Device integration.

Hope you get it to work🙏

**Comment by Andrewb308** [comment]
Thank you so much @TheSpringBoy 
Will try that and let you know

**Comment by YogevBokobza** [comment]
Should be fixed in [#804](https://github.com/TomerFi/aioswitcher/pull/804)

**Comment by TheSpringBoy** [comment]
> Should be fixed in [#804](https://github.com/TomerFi/aioswitcher/pull/804)

There are also SL02 and SL03

**Comment by YogevBokobza** [comment]
> > Should be fixed in [#804](https://github.com/TomerFi/aioswitcher/pull/804)
> 
> There are also SL02 and SL03

Yes, it will be done in a later PR right after that one is merged.
