### ISSUE TITLE
Stabilize flaky tests

### ISSUE THREAD

**Issue by TomerFi** [TomerFi/aioswitcher#713]
### What did you have in mind?

The following test-cases are failing when the running machine's timezone differs from Asia/Jerusalem. Although the underlying devices are meant to work in Asia/Jerusalem, this situation prevents collaborators outside this timezone from passing tests locally. If I remember correctly, these test-cases also fail at a specific time, I think it was 00:00-00:01, but I'm not sure.

https://github.com/TomerFi/aioswitcher/blob/0544a5047ae1e9ae738f5b909b67c9af793e355e/tests/test_schedule_parser.py#L40

https://github.com/TomerFi/aioswitcher/blob/0544a5047ae1e9ae738f5b909b67c9af793e355e/tests/test_schedule_parser.py#L53

https://github.com/TomerFi/aioswitcher/blob/0544a5047ae1e9ae738f5b909b67c9af793e355e/tests/test_schedule_parser.py#L66

https://github.com/TomerFi/aioswitcher/blob/0544a5047ae1e9ae738f5b909b67c9af793e355e/tests/test_schedule_parser.py#L79

**Comment by YogevBokobza** [comment]
Yes I saw this issue when developed the latest PRs..
Need to fix that..

**Comment by YogevBokobza** [comment]
@TomerFi  Is that the fix done in https://github.com/TomerFi/aioswitcher/pull/752 ?

**Comment by TomerFi** [comment]
I don't think so...

**Comment by TomerFi** [comment]
@YogevBokobza #627 seems related to this.
