### ISSUE TITLE
Refactor API Instantiation

### ISSUE THREAD

**Issue by TomerFi** [TomerFi/aioswitcher#778]
### What did you have in mind?

https://github.com/TomerFi/aioswitcher/pull/777#discussion_r1674562168

**Comment by YogevBokobza** [comment]
@thecode @TomerFi 
Regarding this issue, what if we remove SwitcherType1Api and SwitcherType2Api and are left with just SwitcherApi, which will combine all the functions?

Do you see any point in having 2 separate classes?

If you do want to keep SwitcherType1Api and SwitcherType2Api, Can you show me an example of how use SwitcherApi to call SwitcherType1Api and SwitcherType2Api functions? (I tried to do that but I have issues with the function that are on SwitcherApi like the _login)

**Comment by TomerFi** [comment]
Yes, I agree. It would be better if we could have just one API implementation. Regarding how to accomplish that, I'm not sure I'll have time soon to try it. I'll update this issue if anything changes.

**Comment by YogevBokobza** [comment]
> Yes, I agree. It would be better if we could have just one API implementation. Regarding how to accomplish that, I'm not sure I'll have time soon to try it. I'll update this issue if anything changes.

The question is can we just left with 1 SwitcherApi class and combine all the functions together?
Or we want 2 sepereted class like now and 1 more generic class SwitcherApi to make instance of one of them.
The first solution is easy for me it's just removing one class and change the name of the other one, the second option is more difficult for me right now.

What do you think?

**Comment by TomerFi** [comment]
I think one class with all the endpoint funcs is preferred.

**Comment by thecode** [comment]
When making a release we should make sure to mark this as a breaking change
