### ISSUE TITLE
types-requests incompatibility with HA

### ISSUE THREAD

**Issue by epenet** [TomerFi/aioswitcher#791]
### What happened?

#780 introduced a dependency on `types-requests = "^2.31.0.6"`
https://github.com/TomerFi/aioswitcher/blob/841fd6c7ee3748507af9810fdba659f6e2f51de6/pyproject.toml#L23-L26

But HA has it pinned to `2.31.0.3`
https://github.com/home-assistant/core/blob/8cfac68317288fcb88888e369d3bd4302037b77b/requirements_test.txt#L52

It caused issues in my dev environment, preventing me from running the "Install all test requirements" task.

Although it was easily solved - I am surprised that it is a dependency at all....
Should it not be a dev/test-dependency only?

cc @YogevBokobza / @thecode 

### Module Version

4.0.0

### Device Type

Switcher V2

### Firmware Version

.

**Comment by epenet** [comment]
Full error:
```console
 *  Executing task: uv pip install -r requirements_test_all.txt 

  × No solution found when resolving dependencies:
  ╰─▶ Because aioswitcher==4.0.0 depends on types-requests>=2.31.0.6 and you require types-requests==2.31.0.3, we can conclude that your requirements and
      aioswitcher==4.0.0 are incompatible.
      And because you require aioswitcher==4.0.0, we can conclude that the requirements are unsatisfiable.

 *  The terminal process "/usr/bin/zsh '-c', 'uv pip install -r requirements_test_all.txt'" terminated with exit code: 1. 
 *  Press any key to close the terminal.
```

**Comment by TomerFi** [comment]
Good catch @epenet !
