### ISSUE TITLE
CI workflows maintenance

### ISSUE THREAD

**Issue by TomerFi** [TomerFi/aioswitcher#797]
### What did you have in mind?

Our CI workflows require some maintenance. We're seeing warnings in our various workflow runs about old Action versions:
```
The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/checkout@v3, zcong1993/setup-timezone@v2.0.0, actions/setup-python@v4, actions/cache@v3, codecov/codecov-action@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
```

This is a side-effect of removing dependabot more than a year ago. See https://github.com/TomerFi/aioswitcher/commit/b2e5681c0b429b529cf45ea753b124af1f4a97cb.

We also noticed that the various workflows are slower, and caches are invalidated frequently. This is a side effect of having _poetry_ update the dependencies on installation (`--no-update` flag available) and not using the latest versions.

We should consider reintroducing dependabot to this project.

**Comment by TomerFi** [comment]
@thecode @YogevBokobza 
I'm going to work on this. I plan to do some maintenance work on the CI, including reinstating Dependabot.
I will manually bump all dev and ci steps to avoid a stream of PRs by Dependabot.

Do you have any objections/concerns?

**Comment by thecode** [comment]
> @thecode @YogevBokobza 
> I'm going to work on this. I plan to do some maintenance work on the CI, including reinstating Dependabot.
> I will manually bump all dev and ci steps to avoid a stream of PRs by Dependabot.
> 
> Do you have any objections/concerns?

Thanks, sounds good
