### ISSUE TITLE
S11 without entities 

### ISSUE THREAD

**Issue by olivierbutler** [TomerFi/aioswitcher#802]
### What happened?

With the update of HA of 2024.09, my S11 is now visible in HA, but without any entities and also how/where to write in HA the token given by switcher ?

thank you for your support. 

### Module Version

4.0.0

### Device Type

Switcher Runner

### Firmware Version

Runner S11 v2.39

**Comment by olivierbutler** [comment]
[config_entry-switcher_kis-f4fcaed663f196c2d197125b24c96e2e.json](https://github.com/user-attachments/files/16883978/config_entry-switcher_kis-f4fcaed663f196c2d197125b24c96e2e.json)

**Comment by thecode** [comment]
Home Assistant does not support the Runner S11 yet, the supported devices are listed in the integration documentation: https://www.home-assistant.io/integrations/switcher_kis/

In any case this is an issue for Home Assistant not for this library.
