### ISSUE TITLE
Consider python bump

### ISSUE THREAD

**Issue by TomerFi** [TomerFi/aioswitcher#818]
### What did you have in mind?

Our default Python version is 3.10. In CI, we build for 3.9 and 3.10. The current major is 3.13. Should we bump?

@thecode Do you happen to know what version is used/supported by Home Assitant?

**Comment by thecode** [comment]
https://github.com/home-assistant/architecture/blob/master/adr/0020-minimum-supported-python-version.md

Currently Home Assistant is shipped with Python 3.13 and the minimum supported Python version is 3.12
Home Assistant will drop support for Python 3.12 at 2025.2 release (Feb-2025)

I think we should adjust the CI to run using Python 3.13 & 3.12 (mainly if other projects are not using Python 3.13).

For future reference Home Assistant python requirements constants can be seen here:
https://github.com/home-assistant/core/blob/942fbdedcf3f91ce80f7eeab1861687c9a3fdf9a/homeassistant/const.py#L31
